"use client";

import { useState, useEffect, useRef } from "react";
import dynamic from "next/dynamic";
import { Upload, X, Loader2, AlertCircle, Star, Plus } from "lucide-react";
import { serverUploadImage, serverGetUniqueCategories } from "../actions";
import { slugifyTitle, BLOG_CATEGORIES } from "@/lib/blog-admin";
import type { BlogPostInput } from "../actions";

const RichTextEditor = dynamic(() => import("./RichTextEditor"), {
  ssr: false,
  loading: () => <div className="rte-loading">Loading editor…</div>,
});

export interface BlogFormValues {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  author: string;
  category: string;
  cover_image: string;
  read_time: string;
  featured: boolean;
  published: boolean;
  meta_title: string;
  meta_description: string;
}

const DEFAULT_VALUES: BlogFormValues = {
  title: "",
  slug: "",
  excerpt: "",
  content: "",
  author: "",
  category: "AI Strategy",
  cover_image: "",
  read_time: "5 min read",
  featured: false,
  published: false,
  meta_title: "",
  meta_description: "",
};

interface BlogPostFormProps {
  initialValues?: Partial<BlogFormValues>;
  onSubmit: (values: BlogPostInput) => Promise<void>;
  submitLabel?: string;
  loading?: boolean;
  error?: string | null;
}

export default function BlogPostForm({
  initialValues,
  onSubmit,
  submitLabel = "Save Post",
  loading = false,
  error,
}: BlogPostFormProps) {
  const [values, setValues] = useState<BlogFormValues>({ ...DEFAULT_VALUES, ...initialValues });
  const [errors, setErrors] = useState<Partial<Record<keyof BlogFormValues, string>>>({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!initialValues?.slug);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [imgPreview, setImgPreview] = useState<string | null>(initialValues?.cover_image || null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Categories state
  const [categories, setCategories] = useState<string[]>(BLOG_CATEGORIES);
  const [isAddingCategory, setIsAddingCategory] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState("");
  const [catError, setCatError] = useState<string | null>(null);

  // Fetch unique categories
  useEffect(() => {
    serverGetUniqueCategories().then(dbCats => {
      const allCats = Array.from(new Set([...BLOG_CATEGORIES, ...dbCats])).sort();
      setCategories(allCats);
    }).catch(e => console.error("Could not fetch categories", e));
  }, []);

  // Auto-generate slug from title
  useEffect(() => {
    if (slugAutoGenerated && values.title) {
      setValues((v) => ({ ...v, slug: slugifyTitle(v.title) }));
    }
  }, [values.title, slugAutoGenerated]);

  function set<K extends keyof BlogFormValues>(key: K, val: BlogFormValues[K]) {
    setValues((v) => ({ ...v, [key]: val }));
    if (errors[key]) setErrors((e) => ({ ...e, [key]: undefined }));
  }

  function validate(): boolean {
    const e: Partial<Record<keyof BlogFormValues, string>> = {};
    if (!values.title.trim()) e.title = "Title is required";
    if (!values.slug.trim()) e.slug = "Slug is required";
    else if (!/^[a-z0-9-]+$/.test(values.slug)) e.slug = "Slug must be lowercase letters, numbers, and hyphens only";
    if (!values.content.trim()) e.content = "Content is required";
    if (!values.author.trim()) e.author = "Author is required";
    if (!values.category) e.category = "Category is required";
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;
    await onSubmit({
      title: values.title.trim(),
      slug: values.slug.trim(),
      excerpt: values.excerpt.trim() || null,
      content: values.content.trim(),
      author: values.author.trim(),
      category: values.category,
      cover_image: values.cover_image.trim() || null,
      read_time: values.read_time.trim() || null,
      featured: values.featured,
      published: values.published,
      meta_title: values.meta_title.trim() || null,
      meta_description: values.meta_description.trim() || null,
    });
  }

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate
    const allowed = ["image/jpeg", "image/png", "image/webp", "image/gif"];
    if (!allowed.includes(file.type)) {
      setUploadError("Only JPEG, PNG, WebP, or GIF images are allowed.");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      setUploadError("Image must be smaller than 5 MB.");
      return;
    }

    setUploading(true);
    setUploadError(null);
    try {
      const formData = new FormData();
      formData.append('file', file);
      const url = await serverUploadImage(formData);
      set("cover_image", url);
      setImgPreview(url);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Upload failed";
      setUploadError(msg);
    } finally {
      setUploading(false);
    }
  }

  function clearImage() {
    set("cover_image", "");
    setImgPreview(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  }

  function handleAddCategory() {
    const trimmed = newCategoryName.trim();
    if (!trimmed) {
      setCatError("Category name cannot be empty");
      return;
    }
    if (!categories.includes(trimmed)) {
      setCategories(prev => Array.from(new Set([...prev, trimmed])).sort());
    }
    set("category", trimmed);
    setIsAddingCategory(false);
    setNewCategoryName("");
    setCatError(null);
  }

  return (
    <form onSubmit={handleSubmit} className="blog-form" noValidate>
      {error && (
        <div className="form-alert error">
          <AlertCircle size={16} /> {error}
        </div>
      )}

      <div className="form-grid">
        {/* Left column */}
        <div className="form-main">
          {/* Title */}
          <div className="field">
            <label className="field-label">
              Title <span className="required">*</span>
            </label>
            <input
              id="bf-title"
              className={`field-input ${errors.title ? "invalid" : ""}`}
              value={values.title}
              onChange={(e) => set("title", e.target.value)}
              placeholder="My Awesome Blog Post"
            />
            {errors.title && <p className="field-error">{errors.title}</p>}
          </div>

          {/* Slug */}
          <div className="field">
            <label className="field-label">
              Slug <span className="required">*</span>
            </label>
            <div className="slug-wrap">
              <span className="slug-prefix">/blog/</span>
              <input
                id="bf-slug"
                className={`field-input slug-input ${errors.slug ? "invalid" : ""}`}
                value={values.slug}
                onChange={(e) => {
                  setSlugAutoGenerated(false);
                  set("slug", e.target.value);
                }}
                placeholder="my-awesome-blog-post"
              />
            </div>
            {errors.slug && <p className="field-error">{errors.slug}</p>}
            <p className="field-hint">
              Auto-generated from title.{" "}
              {!slugAutoGenerated && (
                <button
                  type="button"
                  className="link-btn"
                  onClick={() => {
                    setSlugAutoGenerated(true);
                    set("slug", slugifyTitle(values.title));
                  }}
                >
                  Re-generate
                </button>
              )}
            </p>
          </div>

          {/* Excerpt */}
          <div className="field">
            <label className="field-label">Excerpt</label>
            <textarea
              id="bf-excerpt"
              className="field-input field-textarea"
              rows={3}
              value={values.excerpt}
              onChange={(e) => set("excerpt", e.target.value)}
              placeholder="A brief summary shown in post listings…"
            />
          </div>

          {/* Content */}
          <div className="field">
            <label className="field-label">
              Content <span className="required">*</span>
            </label>
            <RichTextEditor
              value={values.content}
              onChange={(html) => set("content", html)}
              error={!!errors.content}
            />
            {errors.content && <p className="field-error">{errors.content}</p>}
            <p className="field-hint">Rich text editor — HTML is saved to the database.</p>
          </div>

          {/* SEO section */}
          <div className="section-divider">
            <span>SEO Settings</span>
          </div>

          <div className="field">
            <label className="field-label">Meta Title</label>
            <input
              id="bf-meta-title"
              className="field-input"
              value={values.meta_title}
              onChange={(e) => set("meta_title", e.target.value)}
              placeholder="Overrides page title in search engines"
              maxLength={60}
            />
            <p className="field-hint">{values.meta_title.length}/60 characters</p>
          </div>

          <div className="field">
            <label className="field-label">Meta Description</label>
            <textarea
              id="bf-meta-desc"
              className="field-input field-textarea"
              rows={3}
              value={values.meta_description}
              onChange={(e) => set("meta_description", e.target.value)}
              placeholder="A compelling description for search engine results"
              maxLength={160}
            />
            <p className="field-hint">{values.meta_description.length}/160 characters</p>
          </div>
        </div>

        {/* Right sidebar */}
        <div className="form-sidebar">
          {/* Publish controls */}
          <div className="sidebar-card">
            <h3 className="sidebar-title">Publish</h3>

            <div className="toggle-field">
              <label htmlFor="bf-published" className="toggle-label">
                <div>
                  <p className="toggle-name">Published</p>
                  <p className="toggle-desc">Visible on the public blog</p>
                </div>
                <div
                  id="bf-published"
                  className={`toggle ${values.published ? "on" : ""}`}
                  onClick={() => set("published", !values.published)}
                  role="switch"
                  aria-checked={values.published}
                  tabIndex={0}
                  onKeyDown={(e) => e.key === " " && set("published", !values.published)}
                />
              </label>
            </div>

            <div className="toggle-field">
              <label htmlFor="bf-featured" className="toggle-label">
                <div>
                  <p className="toggle-name">
                    <Star size={13} style={{ display: "inline", color: "#ce2124", marginRight: 4 }} />
                    Featured
                  </p>
                  <p className="toggle-desc">Show in featured section</p>
                </div>
                <div
                  id="bf-featured"
                  className={`toggle ${values.featured ? "on" : ""}`}
                  onClick={() => set("featured", !values.featured)}
                  role="switch"
                  aria-checked={values.featured}
                  tabIndex={0}
                  onKeyDown={(e) => e.key === " " && set("featured", !values.featured)}
                />
              </label>
            </div>

            <button
              id="bf-submit"
              type="submit"
              className="submit-btn"
              disabled={loading}
            >
              {loading ? (
                <>
                  <Loader2 size={16} className="spin" />
                  Saving…
                </>
              ) : (
                submitLabel
              )}
            </button>
          </div>

          {/* Cover image */}
          <div className="sidebar-card">
            <h3 className="sidebar-title">Cover Image</h3>

            {imgPreview ? (
              <div className="img-preview-wrap">
                <img src={imgPreview} alt="Cover preview" className="img-preview" />
                <button type="button" className="img-remove" onClick={clearImage} title="Remove">
                  <X size={14} />
                </button>
              </div>
            ) : (
              <div
                className="img-dropzone"
                onClick={() => fileInputRef.current?.click()}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => e.key === "Enter" && fileInputRef.current?.click()}
              >
                {uploading ? (
                  <Loader2 size={24} className="spin" style={{ color: "#6b7280" }} />
                ) : (
                  <Upload size={24} style={{ color: "#9ca3af" }} />
                )}
                <p className="dropzone-text">
                  {uploading ? "Uploading…" : "Click to upload image"}
                </p>
                <p className="dropzone-hint">JPEG, PNG, WebP up to 5 MB</p>
              </div>
            )}

            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              style={{ display: "none" }}
              onChange={handleFileChange}
            />

            {uploadError && (
              <p className="field-error" style={{ marginTop: 8 }}>
                <AlertCircle size={12} /> {uploadError}
              </p>
            )}

            <div className="field" style={{ marginTop: 12 }}>
              <label className="field-label">Or paste image URL</label>
              <input
                id="bf-cover-image"
                className="field-input"
                value={values.cover_image}
                onChange={(e) => {
                  set("cover_image", e.target.value);
                  setImgPreview(e.target.value || null);
                }}
                placeholder="https://…"
              />
            </div>
          </div>

          {/* Post details */}
          <div className="sidebar-card">
            <h3 className="sidebar-title">Post Details</h3>

            <div className="field">
              <label className="field-label">
                Author <span className="required">*</span>
              </label>
              <input
                id="bf-author"
                className={`field-input ${errors.author ? "invalid" : ""}`}
                value={values.author}
                onChange={(e) => set("author", e.target.value)}
                placeholder="Aiquire Team"
              />
              {errors.author && <p className="field-error">{errors.author}</p>}
            </div>

            <div className="field">
              <label className="field-label">
                Category <span className="required">*</span>
              </label>

              {!isAddingCategory ? (
                <div style={{ display: "flex", gap: "8px" }}>
                  <select
                    id="bf-category"
                    className={`field-input field-select ${errors.category ? "invalid" : ""}`}
                    value={values.category}
                    style={{ flex: 1 }}
                    onChange={(e) => {
                      if (e.target.value === "__new_category__") {
                        setIsAddingCategory(true);
                        setCatError(null);
                      } else {
                        set("category", e.target.value);
                      }
                    }}
                  >
                    <option value="" disabled>Select a category</option>
                    {categories.map((c) => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                    <option value="__new_category__">+ Add New Category</option>
                  </select>
                  <button
                    type="button"
                    className="category-action-btn"
                    onClick={() => setIsAddingCategory(true)}
                    title="Add New Category"
                    style={{ background: "#f3f4f6", color: "#374151", width: '42px' }}
                  >
                    <Plus size={18} />
                  </button>
                </div>
              ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                  <div style={{ display: "flex", gap: "8px" }}>
                    <input
                      type="text"
                      className={`field-input ${catError ? "invalid" : ""}`}
                      placeholder="New Category Name"
                      value={newCategoryName}
                      onChange={(e) => setNewCategoryName(e.target.value)}
                      autoFocus
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                          e.preventDefault();
                          handleAddCategory();
                        } else if (e.key === 'Escape') {
                          setIsAddingCategory(false);
                        }
                      }}
                    />
                    <button
                      type="button"
                      className="category-action-btn"
                      onClick={handleAddCategory}
                      style={{ background: "#ce2124", color: "white" }}
                    >
                      Save
                    </button>
                    <button
                      type="button"
                      className="category-action-btn"
                      onClick={() => setIsAddingCategory(false)}
                      style={{ background: "#f3f4f6", color: "#374151" }}
                    >
                      <X size={16} />
                    </button>
                  </div>
                  {catError && <p className="field-error">{catError}</p>}
                </div>
              )}
              
              {errors.category && !isAddingCategory && <p className="field-error">{errors.category}</p>}
            </div>

            <div className="field">
              <label className="field-label">Read Time</label>
              <input
                id="bf-read-time"
                className="field-input"
                value={values.read_time}
                onChange={(e) => set("read_time", e.target.value)}
                placeholder="5 min read"
              />
            </div>
          </div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .blog-form { width: 100%; }

        .form-alert {
          display: flex; align-items: center; gap: 8px;
          padding: 12px 16px; border-radius: 8px;
          font-size: 14px; margin-bottom: 20px;
        }
        .form-alert.error { background: #fff1f2; color: #991b1b; border: 1px solid #fecaca; }

        .form-grid { display: grid; grid-template-columns: 1fr 320px; gap: 24px; }

        .form-main { display: flex; flex-direction: column; gap: 20px; }
        .form-sidebar { display: flex; flex-direction: column; gap: 16px; }

        .sidebar-card {
          background: white; border-radius: 12px;
          border: 1px solid #f3f4f6; padding: 20px;
        }
        .sidebar-title { font-size: 14px; font-weight: 600; color: #111827; margin: 0 0 16px; }

        /* Fields */
        .field { display: flex; flex-direction: column; gap: 6px; }
        .field-label { font-size: 13px; font-weight: 600; color: #374151; }
        .required { color: #ce2124; }

        .field-input {
          width: 100%; padding: 10px 12px;
          border: 1px solid #e5e7eb; border-radius: 8px;
          font-size: 14px; color: #111827;
          background: white; outline: none;
          transition: border 0.15s;
          font-family: inherit;
        }
        .field-input:focus { border-color: #0F2B46; }
        .field-input.invalid { border-color: #f87171; background: #fef2f2; }
        .field-textarea { resize: vertical; line-height: 1.6; }
        .content-area { min-height: 400px; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 13px; }
        .field-select { cursor: pointer; appearance: auto; }
        .field-error { font-size: 12px; color: #ce2124; display: flex; align-items: center; gap: 4px; }
        .field-hint { font-size: 12px; color: #9ca3af; }

        .slug-wrap { display: flex; align-items: center; background: white; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
        .slug-wrap:focus-within { border-color: #0F2B46; }
        .slug-prefix { padding: 10px 0 10px 12px; font-size: 14px; color: #9ca3af; white-space: nowrap; }
        .slug-input { flex: 1; border: none; padding: 10px 12px; font-size: 14px; color: #111827; outline: none; }
        .slug-input.invalid { background: #fef2f2; }

        .category-action-btn { display: flex; align-items: center; justify-content: center; height: 100%; border: none; border-radius: 8px; cursor: pointer; transition: opacity 0.15s; padding: 0 12px; font-size: 13px; font-weight: 500;}
        .category-action-btn:hover { opacity: 0.9; }

        .link-btn { background: none; border: none; color: #2563eb; font-size: 12px; cursor: pointer; text-decoration: underline; padding: 0; }

        .section-divider { display: flex; align-items: center; gap: 12px; margin: 8px 0 4px; }
        .section-divider::before, .section-divider::after { content: ''; flex: 1; height: 1px; background: #e5e7eb; }
        .section-divider span { font-size: 12px; font-weight: 600; color: #9ca3af; letter-spacing: 0.06em; text-transform: uppercase; white-space: nowrap; }

        /* Toggle */
        .toggle-field { padding: 10px 0; border-bottom: 1px solid #f3f4f6; }
        .toggle-field:last-of-type { border-bottom: none; margin-bottom: 12px; }
        .toggle-label { display: flex; align-items: center; justify-content: space-between; cursor: pointer; }
        .toggle-name { font-size: 13px; font-weight: 500; color: #111827; margin: 0 0 2px; }
        .toggle-desc { font-size: 12px; color: #9ca3af; margin: 0; }

        .toggle {
          width: 40px; height: 22px;
          background: #d1d5db; border-radius: 99px;
          position: relative; flex-shrink: 0;
          cursor: pointer; transition: background 0.2s;
          outline-offset: 2px;
        }
        .toggle:focus-visible { outline: 2px solid #0F2B46; }
        .toggle::after {
          content: ''; position: absolute;
          top: 3px; left: 3px;
          width: 16px; height: 16px;
          background: white; border-radius: 50%;
          transition: transform 0.2s;
        }
        .toggle.on { background: #ce2124; }
        .toggle.on::after { transform: translateX(18px); }

        .submit-btn {
          width: 100%; padding: 11px;
          background: #0F2B46; color: white;
          border: none; border-radius: 8px;
          font-size: 14px; font-weight: 600;
          cursor: pointer; transition: background 0.15s;
          display: flex; align-items: center; justify-content: center; gap: 8px;
          margin-top: 4px;
        }
        .submit-btn:hover:not(:disabled) { background: #1a4a6b; }
        .submit-btn:disabled { opacity: 0.5; cursor: not-allowed; }

        /* Image */
        .img-preview-wrap { position: relative; border-radius: 8px; overflow: hidden; }
        .img-preview { width: 100%; height: 180px; object-fit: cover; display: block; border-radius: 8px; }
        .img-remove {
          position: absolute; top: 8px; right: 8px;
          background: rgba(0,0,0,0.6); color: white;
          border: none; border-radius: 4px; padding: 4px 6px;
          cursor: pointer; display: flex; align-items: center;
        }
        .img-remove:hover { background: rgba(0,0,0,0.8); }

        .img-dropzone {
          border: 2px dashed #e5e7eb; border-radius: 8px;
          padding: 28px 16px;
          display: flex; flex-direction: column; align-items: center; gap: 6px;
          cursor: pointer; transition: border-color 0.15s;
          text-align: center;
        }
        .img-dropzone:hover { border-color: #0F2B46; }
        .dropzone-text { font-size: 13px; font-weight: 500; color: #374151; margin: 0; }
        .dropzone-hint { font-size: 12px; color: #9ca3af; margin: 0; }

        .spin { animation: spin 0.8s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }

        @media (max-width: 1100px) {
          .form-grid { grid-template-columns: 1fr; }
          .form-sidebar { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        }
        @media (max-width: 640px) {
          .form-sidebar { grid-template-columns: 1fr; }
        }
      `}} />
    </form>
  );
}
